# -*- coding: utf-8 -*-
"""베어로보틱스 코테.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vHAC7C1o19x_S12YmNEVHN0_eHWARSdB
"""

# 1 카드 삽입
# 2. pin 입력
# 3, 계좌 선택
# 4. 잔액 조회 / 입금 / 출금


def ATM():

  while True:
    real_pin_num="123456"
    account_num=4
    my_money=2000

    print("카드를 삽입해주세요")
    get_pin_num=str(input("PIN 번호를 입력해주세요:"))

    if real_pin_num==get_pin_num:
      print("PIN 번호가 일치합니다")

      while True:
        get_account_num=int(input("계좌를 선택해주세요1 2 3 4:"))

        if get_account_num==1:
          print("1번 계좌 선택")
          break
        elif get_account_num==2:
          print("2번 계좌 선택")
          break
        elif get_account_num==3:
          print("3번 계좌 선택")
          break
        elif get_account_num==4:
          print("4번 계좌 선택")
          break
        else:
          print("일치하는 계좌 없습니다")

    else:
      print("PIN 번호가 일치하지 않습니다")

    while True:
      get_select_num=int(input(" 1. 잔액 조회 2. 입금 3. 출금 4 종료:"))

      if get_select_num==1:
        print("잔액 조회:",my_money,"원")
      elif get_select_num==2:
        plus_money=int(input("돈을 입금해주세요:"))
        if plus_money%1000 != 0:
          print("1000원 단위만 입금 가능")
        else:
          my_money+=plus_money
          print("입금 후 잔액:",my_money,"원")
      elif get_select_num==3:
        minus_money=int(input("출금할 돈 입력:"))
        if minus_money <= my_money:
          if minus_money%1000 != 0:
            print("1000원 단위만 출금 가능")
          else:
            my_money-=minus_money
            print("출금 후 잔액:",my_money,"원")
        else:
          print("잔액 부족 현재 잔액",my_money,"원")
      elif get_select_num==4:
        print("프로그램 종료")
        break
      else:
        print("잘못된 입력")
    break



ATM()